// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: binding.proto

package com.google.daggerquery.protobuf.autogen;

public final class BindingProto {
  private BindingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BindingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dagerquery.models.Binding)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string component_name = 1;</code>
     * @return Whether the componentName field is set.
     */
    boolean hasComponentName();
    /**
     * <code>required string component_name = 1;</code>
     * @return The componentName.
     */
    java.lang.String getComponentName();
    /**
     * <code>required string component_name = 1;</code>
     * @return The bytes for componentName.
     */
    com.google.protobuf.ByteString
        getComponentNameBytes();

    /**
     * <code>required bool is_component = 2;</code>
     * @return Whether the isComponent field is set.
     */
    boolean hasIsComponent();
    /**
     * <code>required bool is_component = 2;</code>
     * @return The isComponent.
     */
    boolean getIsComponent();

    /**
     * <code>required bool is_missing = 3;</code>
     * @return Whether the isMissing field is set.
     */
    boolean hasIsMissing();
    /**
     * <code>required bool is_missing = 3;</code>
     * @return The isMissing.
     */
    boolean getIsMissing();

    /**
     * <code>optional string key = 4;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>optional string key = 4;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 4;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional string element = 5;</code>
     * @return Whether the element field is set.
     */
    boolean hasElement();
    /**
     * <code>optional string element = 5;</code>
     * @return The element.
     */
    java.lang.String getElement();
    /**
     * <code>optional string element = 5;</code>
     * @return The bytes for element.
     */
    com.google.protobuf.ByteString
        getElementBytes();

    /**
     * <code>optional string module = 6;</code>
     * @return Whether the module field is set.
     */
    boolean hasModule();
    /**
     * <code>optional string module = 6;</code>
     * @return The module.
     */
    java.lang.String getModule();
    /**
     * <code>optional string module = 6;</code>
     * @return The bytes for module.
     */
    com.google.protobuf.ByteString
        getModuleBytes();

    /**
     * <code>optional string scope = 7;</code>
     * @return Whether the scope field is set.
     */
    boolean hasScope();
    /**
     * <code>optional string scope = 7;</code>
     * @return The scope.
     */
    java.lang.String getScope();
    /**
     * <code>optional string scope = 7;</code>
     * @return The bytes for scope.
     */
    com.google.protobuf.ByteString
        getScopeBytes();

    /**
     * <code>optional .dagerquery.models.Binding.Kind kind = 8;</code>
     * @return Whether the kind field is set.
     */
    boolean hasKind();
    /**
     * <code>optional .dagerquery.models.Binding.Kind kind = 8;</code>
     * @return The kind.
     */
    BindingProto.Binding.Kind getKind();
  }
  /**
   * Protobuf type {@code dagerquery.models.Binding}
   */
  public static final class Binding extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dagerquery.models.Binding)
      BindingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Binding.newBuilder() to construct.
    private Binding(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Binding() {
      componentName_ = "";
      key_ = "";
      element_ = "";
      module_ = "";
      scope_ = "";
      kind_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Binding(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              componentName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isComponent_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isMissing_ = input.readBool();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              key_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              element_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              module_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              scope_ = bs;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              BindingProto.Binding.Kind value = BindingProto.Binding.Kind.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                kind_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BindingProto.internal_static_dagerquery_models_Binding_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BindingProto.internal_static_dagerquery_models_Binding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BindingProto.Binding.class, BindingProto.Binding.Builder.class);
    }

    /**
     * Protobuf enum {@code dagerquery.models.Binding.Kind}
     */
    public enum Kind
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INJECTION = 0;</code>
       */
      INJECTION(0),
      /**
       * <code>PROVISION = 1;</code>
       */
      PROVISION(1),
      /**
       * <code>COMPONENT = 2;</code>
       */
      COMPONENT(2),
      /**
       * <code>COMPONENT_PROVISION = 3;</code>
       */
      COMPONENT_PROVISION(3),
      /**
       * <code>COMPONENT_DEPENDENCY = 4;</code>
       */
      COMPONENT_DEPENDENCY(4),
      /**
       * <code>MEMBERS_INJECTOR = 5;</code>
       */
      MEMBERS_INJECTOR(5),
      /**
       * <code>SUBCOMPONENT_CREATOR = 6;</code>
       */
      SUBCOMPONENT_CREATOR(6),
      /**
       * <code>BOUND_INSTANCE = 7;</code>
       */
      BOUND_INSTANCE(7),
      /**
       * <code>PRODUCTION = 8;</code>
       */
      PRODUCTION(8),
      /**
       * <code>COMPONENT_PRODUCTION = 9;</code>
       */
      COMPONENT_PRODUCTION(9),
      /**
       * <code>MULTIBOUND_SET = 10;</code>
       */
      MULTIBOUND_SET(10),
      /**
       * <code>MULTIBOUND_MAP = 11;</code>
       */
      MULTIBOUND_MAP(11),
      /**
       * <code>OPTIONAL = 12;</code>
       */
      OPTIONAL(12),
      /**
       * <code>DELEGATE = 13;</code>
       */
      DELEGATE(13),
      /**
       * <code>MEMBERS_INJECTION = 14;</code>
       */
      MEMBERS_INJECTION(14),
      ;

      /**
       * <code>INJECTION = 0;</code>
       */
      public static final int INJECTION_VALUE = 0;
      /**
       * <code>PROVISION = 1;</code>
       */
      public static final int PROVISION_VALUE = 1;
      /**
       * <code>COMPONENT = 2;</code>
       */
      public static final int COMPONENT_VALUE = 2;
      /**
       * <code>COMPONENT_PROVISION = 3;</code>
       */
      public static final int COMPONENT_PROVISION_VALUE = 3;
      /**
       * <code>COMPONENT_DEPENDENCY = 4;</code>
       */
      public static final int COMPONENT_DEPENDENCY_VALUE = 4;
      /**
       * <code>MEMBERS_INJECTOR = 5;</code>
       */
      public static final int MEMBERS_INJECTOR_VALUE = 5;
      /**
       * <code>SUBCOMPONENT_CREATOR = 6;</code>
       */
      public static final int SUBCOMPONENT_CREATOR_VALUE = 6;
      /**
       * <code>BOUND_INSTANCE = 7;</code>
       */
      public static final int BOUND_INSTANCE_VALUE = 7;
      /**
       * <code>PRODUCTION = 8;</code>
       */
      public static final int PRODUCTION_VALUE = 8;
      /**
       * <code>COMPONENT_PRODUCTION = 9;</code>
       */
      public static final int COMPONENT_PRODUCTION_VALUE = 9;
      /**
       * <code>MULTIBOUND_SET = 10;</code>
       */
      public static final int MULTIBOUND_SET_VALUE = 10;
      /**
       * <code>MULTIBOUND_MAP = 11;</code>
       */
      public static final int MULTIBOUND_MAP_VALUE = 11;
      /**
       * <code>OPTIONAL = 12;</code>
       */
      public static final int OPTIONAL_VALUE = 12;
      /**
       * <code>DELEGATE = 13;</code>
       */
      public static final int DELEGATE_VALUE = 13;
      /**
       * <code>MEMBERS_INJECTION = 14;</code>
       */
      public static final int MEMBERS_INJECTION_VALUE = 14;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Kind valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Kind forNumber(int value) {
        switch (value) {
          case 0: return INJECTION;
          case 1: return PROVISION;
          case 2: return COMPONENT;
          case 3: return COMPONENT_PROVISION;
          case 4: return COMPONENT_DEPENDENCY;
          case 5: return MEMBERS_INJECTOR;
          case 6: return SUBCOMPONENT_CREATOR;
          case 7: return BOUND_INSTANCE;
          case 8: return PRODUCTION;
          case 9: return COMPONENT_PRODUCTION;
          case 10: return MULTIBOUND_SET;
          case 11: return MULTIBOUND_MAP;
          case 12: return OPTIONAL;
          case 13: return DELEGATE;
          case 14: return MEMBERS_INJECTION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Kind>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Kind> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Kind>() {
              public Kind findValueByNumber(int number) {
                return Kind.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return BindingProto.Binding.getDescriptor().getEnumTypes().get(0);
      }

      private static final Kind[] VALUES = values();

      public static Kind valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Kind(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dagerquery.models.Binding.Kind)
    }

    private int bitField0_;
    public static final int COMPONENT_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object componentName_;
    /**
     * <code>required string component_name = 1;</code>
     * @return Whether the componentName field is set.
     */
    @java.lang.Override
    public boolean hasComponentName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string component_name = 1;</code>
     * @return The componentName.
     */
    @java.lang.Override
    public java.lang.String getComponentName() {
      java.lang.Object ref = componentName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          componentName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string component_name = 1;</code>
     * @return The bytes for componentName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getComponentNameBytes() {
      java.lang.Object ref = componentName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        componentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_COMPONENT_FIELD_NUMBER = 2;
    private boolean isComponent_;
    /**
     * <code>required bool is_component = 2;</code>
     * @return Whether the isComponent field is set.
     */
    @java.lang.Override
    public boolean hasIsComponent() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required bool is_component = 2;</code>
     * @return The isComponent.
     */
    @java.lang.Override
    public boolean getIsComponent() {
      return isComponent_;
    }

    public static final int IS_MISSING_FIELD_NUMBER = 3;
    private boolean isMissing_;
    /**
     * <code>required bool is_missing = 3;</code>
     * @return Whether the isMissing field is set.
     */
    @java.lang.Override
    public boolean hasIsMissing() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bool is_missing = 3;</code>
     * @return The isMissing.
     */
    @java.lang.Override
    public boolean getIsMissing() {
      return isMissing_;
    }

    public static final int KEY_FIELD_NUMBER = 4;
    private volatile java.lang.Object key_;
    /**
     * <code>optional string key = 4;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string key = 4;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 4;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ELEMENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object element_;
    /**
     * <code>optional string element = 5;</code>
     * @return Whether the element field is set.
     */
    @java.lang.Override
    public boolean hasElement() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string element = 5;</code>
     * @return The element.
     */
    @java.lang.Override
    public java.lang.String getElement() {
      java.lang.Object ref = element_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          element_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string element = 5;</code>
     * @return The bytes for element.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getElementBytes() {
      java.lang.Object ref = element_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        element_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODULE_FIELD_NUMBER = 6;
    private volatile java.lang.Object module_;
    /**
     * <code>optional string module = 6;</code>
     * @return Whether the module field is set.
     */
    @java.lang.Override
    public boolean hasModule() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string module = 6;</code>
     * @return The module.
     */
    @java.lang.Override
    public java.lang.String getModule() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          module_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string module = 6;</code>
     * @return The bytes for module.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModuleBytes() {
      java.lang.Object ref = module_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        module_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCOPE_FIELD_NUMBER = 7;
    private volatile java.lang.Object scope_;
    /**
     * <code>optional string scope = 7;</code>
     * @return Whether the scope field is set.
     */
    @java.lang.Override
    public boolean hasScope() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string scope = 7;</code>
     * @return The scope.
     */
    @java.lang.Override
    public java.lang.String getScope() {
      java.lang.Object ref = scope_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          scope_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string scope = 7;</code>
     * @return The bytes for scope.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getScopeBytes() {
      java.lang.Object ref = scope_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scope_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KIND_FIELD_NUMBER = 8;
    private int kind_;
    /**
     * <code>optional .dagerquery.models.Binding.Kind kind = 8;</code>
     * @return Whether the kind field is set.
     */
    @java.lang.Override public boolean hasKind() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .dagerquery.models.Binding.Kind kind = 8;</code>
     * @return The kind.
     */
    @java.lang.Override public BindingProto.Binding.Kind getKind() {
      @SuppressWarnings("deprecation")
      BindingProto.Binding.Kind result = BindingProto.Binding.Kind.valueOf(kind_);
      return result == null ? BindingProto.Binding.Kind.INJECTION : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasComponentName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsComponent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsMissing()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, componentName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, isComponent_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBool(3, isMissing_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, key_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, element_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, module_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, scope_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeEnum(8, kind_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, componentName_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isComponent_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isMissing_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, key_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, element_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, module_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, scope_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, kind_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BindingProto.Binding)) {
        return super.equals(obj);
      }
      BindingProto.Binding other = (BindingProto.Binding) obj;

      if (hasComponentName() != other.hasComponentName()) return false;
      if (hasComponentName()) {
        if (!getComponentName()
            .equals(other.getComponentName())) return false;
      }
      if (hasIsComponent() != other.hasIsComponent()) return false;
      if (hasIsComponent()) {
        if (getIsComponent()
            != other.getIsComponent()) return false;
      }
      if (hasIsMissing() != other.hasIsMissing()) return false;
      if (hasIsMissing()) {
        if (getIsMissing()
            != other.getIsMissing()) return false;
      }
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasElement() != other.hasElement()) return false;
      if (hasElement()) {
        if (!getElement()
            .equals(other.getElement())) return false;
      }
      if (hasModule() != other.hasModule()) return false;
      if (hasModule()) {
        if (!getModule()
            .equals(other.getModule())) return false;
      }
      if (hasScope() != other.hasScope()) return false;
      if (hasScope()) {
        if (!getScope()
            .equals(other.getScope())) return false;
      }
      if (hasKind() != other.hasKind()) return false;
      if (hasKind()) {
        if (kind_ != other.kind_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasComponentName()) {
        hash = (37 * hash) + COMPONENT_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getComponentName().hashCode();
      }
      if (hasIsComponent()) {
        hash = (37 * hash) + IS_COMPONENT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsComponent());
      }
      if (hasIsMissing()) {
        hash = (37 * hash) + IS_MISSING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsMissing());
      }
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasElement()) {
        hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getElement().hashCode();
      }
      if (hasModule()) {
        hash = (37 * hash) + MODULE_FIELD_NUMBER;
        hash = (53 * hash) + getModule().hashCode();
      }
      if (hasScope()) {
        hash = (37 * hash) + SCOPE_FIELD_NUMBER;
        hash = (53 * hash) + getScope().hashCode();
      }
      if (hasKind()) {
        hash = (37 * hash) + KIND_FIELD_NUMBER;
        hash = (53 * hash) + kind_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BindingProto.Binding parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BindingProto.Binding parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BindingProto.Binding parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BindingProto.Binding parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BindingProto.Binding parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BindingProto.Binding parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BindingProto.Binding parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BindingProto.Binding parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BindingProto.Binding parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BindingProto.Binding parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BindingProto.Binding parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BindingProto.Binding parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BindingProto.Binding prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dagerquery.models.Binding}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dagerquery.models.Binding)
        BindingProto.BindingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BindingProto.internal_static_dagerquery_models_Binding_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BindingProto.internal_static_dagerquery_models_Binding_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BindingProto.Binding.class, BindingProto.Binding.Builder.class);
      }

      // Construct using com.google.daggerquery.protobuf.autogen.BindingProto.Binding.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        componentName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        isComponent_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        isMissing_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        element_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        module_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        scope_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        kind_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BindingProto.internal_static_dagerquery_models_Binding_descriptor;
      }

      @java.lang.Override
      public BindingProto.Binding getDefaultInstanceForType() {
        return BindingProto.Binding.getDefaultInstance();
      }

      @java.lang.Override
      public BindingProto.Binding build() {
        BindingProto.Binding result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BindingProto.Binding buildPartial() {
        BindingProto.Binding result = new BindingProto.Binding(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.componentName_ = componentName_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.isComponent_ = isComponent_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.isMissing_ = isMissing_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.element_ = element_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.module_ = module_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.scope_ = scope_;
        if (((from_bitField0_ & 0x00000080) != 0)) {
          to_bitField0_ |= 0x00000080;
        }
        result.kind_ = kind_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BindingProto.Binding) {
          return mergeFrom((BindingProto.Binding)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BindingProto.Binding other) {
        if (other == BindingProto.Binding.getDefaultInstance()) return this;
        if (other.hasComponentName()) {
          bitField0_ |= 0x00000001;
          componentName_ = other.componentName_;
          onChanged();
        }
        if (other.hasIsComponent()) {
          setIsComponent(other.getIsComponent());
        }
        if (other.hasIsMissing()) {
          setIsMissing(other.getIsMissing());
        }
        if (other.hasKey()) {
          bitField0_ |= 0x00000008;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasElement()) {
          bitField0_ |= 0x00000010;
          element_ = other.element_;
          onChanged();
        }
        if (other.hasModule()) {
          bitField0_ |= 0x00000020;
          module_ = other.module_;
          onChanged();
        }
        if (other.hasScope()) {
          bitField0_ |= 0x00000040;
          scope_ = other.scope_;
          onChanged();
        }
        if (other.hasKind()) {
          setKind(other.getKind());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasComponentName()) {
          return false;
        }
        if (!hasIsComponent()) {
          return false;
        }
        if (!hasIsMissing()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BindingProto.Binding parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BindingProto.Binding) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object componentName_ = "";
      /**
       * <code>required string component_name = 1;</code>
       * @return Whether the componentName field is set.
       */
      public boolean hasComponentName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string component_name = 1;</code>
       * @return The componentName.
       */
      public java.lang.String getComponentName() {
        java.lang.Object ref = componentName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            componentName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string component_name = 1;</code>
       * @return The bytes for componentName.
       */
      public com.google.protobuf.ByteString
          getComponentNameBytes() {
        java.lang.Object ref = componentName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          componentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string component_name = 1;</code>
       * @param value The componentName to set.
       * @return This builder for chaining.
       */
      public Builder setComponentName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        componentName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string component_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearComponentName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        componentName_ = getDefaultInstance().getComponentName();
        onChanged();
        return this;
      }
      /**
       * <code>required string component_name = 1;</code>
       * @param value The bytes for componentName to set.
       * @return This builder for chaining.
       */
      public Builder setComponentNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        componentName_ = value;
        onChanged();
        return this;
      }

      private boolean isComponent_ ;
      /**
       * <code>required bool is_component = 2;</code>
       * @return Whether the isComponent field is set.
       */
      @java.lang.Override
      public boolean hasIsComponent() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required bool is_component = 2;</code>
       * @return The isComponent.
       */
      @java.lang.Override
      public boolean getIsComponent() {
        return isComponent_;
      }
      /**
       * <code>required bool is_component = 2;</code>
       * @param value The isComponent to set.
       * @return This builder for chaining.
       */
      public Builder setIsComponent(boolean value) {
        bitField0_ |= 0x00000002;
        isComponent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool is_component = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsComponent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isComponent_ = false;
        onChanged();
        return this;
      }

      private boolean isMissing_ ;
      /**
       * <code>required bool is_missing = 3;</code>
       * @return Whether the isMissing field is set.
       */
      @java.lang.Override
      public boolean hasIsMissing() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bool is_missing = 3;</code>
       * @return The isMissing.
       */
      @java.lang.Override
      public boolean getIsMissing() {
        return isMissing_;
      }
      /**
       * <code>required bool is_missing = 3;</code>
       * @param value The isMissing to set.
       * @return This builder for chaining.
       */
      public Builder setIsMissing(boolean value) {
        bitField0_ |= 0x00000004;
        isMissing_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool is_missing = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsMissing() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isMissing_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 4;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string key = 4;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 4;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 4;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000008);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 4;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        key_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object element_ = "";
      /**
       * <code>optional string element = 5;</code>
       * @return Whether the element field is set.
       */
      public boolean hasElement() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string element = 5;</code>
       * @return The element.
       */
      public java.lang.String getElement() {
        java.lang.Object ref = element_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            element_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string element = 5;</code>
       * @return The bytes for element.
       */
      public com.google.protobuf.ByteString
          getElementBytes() {
        java.lang.Object ref = element_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          element_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string element = 5;</code>
       * @param value The element to set.
       * @return This builder for chaining.
       */
      public Builder setElement(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        element_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string element = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearElement() {
        bitField0_ = (bitField0_ & ~0x00000010);
        element_ = getDefaultInstance().getElement();
        onChanged();
        return this;
      }
      /**
       * <code>optional string element = 5;</code>
       * @param value The bytes for element to set.
       * @return This builder for chaining.
       */
      public Builder setElementBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        element_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object module_ = "";
      /**
       * <code>optional string module = 6;</code>
       * @return Whether the module field is set.
       */
      public boolean hasModule() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string module = 6;</code>
       * @return The module.
       */
      public java.lang.String getModule() {
        java.lang.Object ref = module_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            module_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string module = 6;</code>
       * @return The bytes for module.
       */
      public com.google.protobuf.ByteString
          getModuleBytes() {
        java.lang.Object ref = module_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          module_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string module = 6;</code>
       * @param value The module to set.
       * @return This builder for chaining.
       */
      public Builder setModule(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        module_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string module = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearModule() {
        bitField0_ = (bitField0_ & ~0x00000020);
        module_ = getDefaultInstance().getModule();
        onChanged();
        return this;
      }
      /**
       * <code>optional string module = 6;</code>
       * @param value The bytes for module to set.
       * @return This builder for chaining.
       */
      public Builder setModuleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        module_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object scope_ = "";
      /**
       * <code>optional string scope = 7;</code>
       * @return Whether the scope field is set.
       */
      public boolean hasScope() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string scope = 7;</code>
       * @return The scope.
       */
      public java.lang.String getScope() {
        java.lang.Object ref = scope_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            scope_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string scope = 7;</code>
       * @return The bytes for scope.
       */
      public com.google.protobuf.ByteString
          getScopeBytes() {
        java.lang.Object ref = scope_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scope_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string scope = 7;</code>
       * @param value The scope to set.
       * @return This builder for chaining.
       */
      public Builder setScope(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        scope_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string scope = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearScope() {
        bitField0_ = (bitField0_ & ~0x00000040);
        scope_ = getDefaultInstance().getScope();
        onChanged();
        return this;
      }
      /**
       * <code>optional string scope = 7;</code>
       * @param value The bytes for scope to set.
       * @return This builder for chaining.
       */
      public Builder setScopeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        scope_ = value;
        onChanged();
        return this;
      }

      private int kind_ = 0;
      /**
       * <code>optional .dagerquery.models.Binding.Kind kind = 8;</code>
       * @return Whether the kind field is set.
       */
      @java.lang.Override public boolean hasKind() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional .dagerquery.models.Binding.Kind kind = 8;</code>
       * @return The kind.
       */
      @java.lang.Override
      public BindingProto.Binding.Kind getKind() {
        @SuppressWarnings("deprecation")
        BindingProto.Binding.Kind result = BindingProto.Binding.Kind.valueOf(kind_);
        return result == null ? BindingProto.Binding.Kind.INJECTION : result;
      }
      /**
       * <code>optional .dagerquery.models.Binding.Kind kind = 8;</code>
       * @param value The kind to set.
       * @return This builder for chaining.
       */
      public Builder setKind(BindingProto.Binding.Kind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        kind_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .dagerquery.models.Binding.Kind kind = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000080);
        kind_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dagerquery.models.Binding)
    }

    // @@protoc_insertion_point(class_scope:dagerquery.models.Binding)
    private static final BindingProto.Binding DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BindingProto.Binding();
    }

    public static BindingProto.Binding getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Binding>
        PARSER = new com.google.protobuf.AbstractParser<Binding>() {
      @java.lang.Override
      public Binding parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Binding(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Binding> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Binding> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BindingProto.Binding getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dagerquery_models_Binding_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dagerquery_models_Binding_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbinding.proto\022\021dagerquery.models\"\351\003\n\007B" +
      "inding\022\026\n\016component_name\030\001 \002(\t\022\024\n\014is_com" +
      "ponent\030\002 \002(\010\022\022\n\nis_missing\030\003 \002(\010\022\013\n\003key\030" +
      "\004 \001(\t\022\017\n\007element\030\005 \001(\t\022\016\n\006module\030\006 \001(\t\022\r" +
      "\n\005scope\030\007 \001(\t\022-\n\004kind\030\010 \001(\0162\037.dagerquery" +
      ".models.Binding.Kind\"\257\002\n\004Kind\022\r\n\tINJECTI" +
      "ON\020\000\022\r\n\tPROVISION\020\001\022\r\n\tCOMPONENT\020\002\022\027\n\023CO" +
      "MPONENT_PROVISION\020\003\022\030\n\024COMPONENT_DEPENDE" +
      "NCY\020\004\022\024\n\020MEMBERS_INJECTOR\020\005\022\030\n\024SUBCOMPON" +
      "ENT_CREATOR\020\006\022\022\n\016BOUND_INSTANCE\020\007\022\016\n\nPRO" +
      "DUCTION\020\010\022\030\n\024COMPONENT_PRODUCTION\020\t\022\022\n\016M" +
      "ULTIBOUND_SET\020\n\022\022\n\016MULTIBOUND_MAP\020\013\022\014\n\010O" +
      "PTIONAL\020\014\022\014\n\010DELEGATE\020\r\022\025\n\021MEMBERS_INJEC" +
      "TION\020\016B/\n\037com.google.daggerquery.protobu" +
      "fB\014BindingProto"
    };

    internal_static_dagerquery_models_Binding_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dagerquery_models_Binding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dagerquery_models_Binding_descriptor,
        new java.lang.String[] { "ComponentName", "IsComponent", "IsMissing", "Key", "Element", "Module", "Scope", "Kind", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
