// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: binding_graph.proto

package com.google.daggerquery.protobuf.autogen;

public final class BindingGraphProto {
  private BindingGraphProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BindingGraphOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dagerquery.models.BindingGraph)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
     */
    int getAdjacencyListCount();
    /**
     * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
     */
    boolean containsAdjacencyList(
        java.lang.String key);
    /**
     * Use {@link #getAdjacencyListMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies>
    getAdjacencyList();
    /**
     * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
     */
    java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies>
    getAdjacencyListMap();
    /**
     * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
     */

    BindingGraphProto.BindingGraph.ListWithDependencies getAdjacencyListOrDefault(
        java.lang.String key,
        BindingGraphProto.BindingGraph.ListWithDependencies defaultValue);
    /**
     * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
     */

    BindingGraphProto.BindingGraph.ListWithDependencies getAdjacencyListOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code dagerquery.models.BindingGraph}
   */
  public static final class BindingGraph extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dagerquery.models.BindingGraph)
      BindingGraphOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BindingGraph.newBuilder() to construct.
    private BindingGraph(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BindingGraph() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BindingGraph(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                adjacencyList_ = com.google.protobuf.MapField.newMapField(
                    AdjacencyListDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies>
              adjacencyList__ = input.readMessage(
                  AdjacencyListDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              adjacencyList_.getMutableMap().put(
                  adjacencyList__.getKey(), adjacencyList__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetAdjacencyList();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BindingGraphProto.BindingGraph.class, BindingGraphProto.BindingGraph.Builder.class);
    }

    public interface ListWithDependenciesOrBuilder extends
        // @@protoc_insertion_point(interface_extends:dagerquery.models.BindingGraph.ListWithDependencies)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      java.util.List<DependencyProto.Dependency>
          getDependencyList();
      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      DependencyProto.Dependency getDependency(int index);
      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      int getDependencyCount();
      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      java.util.List<? extends DependencyProto.DependencyOrBuilder>
          getDependencyOrBuilderList();
      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      DependencyProto.DependencyOrBuilder getDependencyOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code dagerquery.models.BindingGraph.ListWithDependencies}
     */
    public static final class ListWithDependencies extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:dagerquery.models.BindingGraph.ListWithDependencies)
        ListWithDependenciesOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ListWithDependencies.newBuilder() to construct.
      private ListWithDependencies(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ListWithDependencies() {
        dependency_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ListWithDependencies(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  dependency_ = new java.util.ArrayList<DependencyProto.Dependency>();
                  mutable_bitField0_ |= 0x00000001;
                }
                dependency_.add(
                    input.readMessage(DependencyProto.Dependency.PARSER, extensionRegistry));
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            dependency_ = java.util.Collections.unmodifiableList(dependency_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_ListWithDependencies_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_ListWithDependencies_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BindingGraphProto.BindingGraph.ListWithDependencies.class, BindingGraphProto.BindingGraph.ListWithDependencies.Builder.class);
      }

      public static final int DEPENDENCY_FIELD_NUMBER = 1;
      private java.util.List<DependencyProto.Dependency> dependency_;
      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      @java.lang.Override
      public java.util.List<DependencyProto.Dependency> getDependencyList() {
        return dependency_;
      }
      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      @java.lang.Override
      public java.util.List<? extends DependencyProto.DependencyOrBuilder>
          getDependencyOrBuilderList() {
        return dependency_;
      }
      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      @java.lang.Override
      public int getDependencyCount() {
        return dependency_.size();
      }
      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      @java.lang.Override
      public DependencyProto.Dependency getDependency(int index) {
        return dependency_.get(index);
      }
      /**
       * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
       */
      @java.lang.Override
      public DependencyProto.DependencyOrBuilder getDependencyOrBuilder(
          int index) {
        return dependency_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        for (int i = 0; i < getDependencyCount(); i++) {
          if (!getDependency(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < dependency_.size(); i++) {
          output.writeMessage(1, dependency_.get(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < dependency_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, dependency_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof BindingGraphProto.BindingGraph.ListWithDependencies)) {
          return super.equals(obj);
        }
        BindingGraphProto.BindingGraph.ListWithDependencies other = (BindingGraphProto.BindingGraph.ListWithDependencies) obj;

        if (!getDependencyList()
            .equals(other.getDependencyList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getDependencyCount() > 0) {
          hash = (37 * hash) + DEPENDENCY_FIELD_NUMBER;
          hash = (53 * hash) + getDependencyList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static BindingGraphProto.BindingGraph.ListWithDependencies parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(BindingGraphProto.BindingGraph.ListWithDependencies prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code dagerquery.models.BindingGraph.ListWithDependencies}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:dagerquery.models.BindingGraph.ListWithDependencies)
          BindingGraphProto.BindingGraph.ListWithDependenciesOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_ListWithDependencies_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_ListWithDependencies_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  BindingGraphProto.BindingGraph.ListWithDependencies.class, BindingGraphProto.BindingGraph.ListWithDependencies.Builder.class);
        }

        // Construct using com.google.daggerquery.protobuf.autogen.BindingGraphProto.BindingGraph.ListWithDependencies.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getDependencyFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (dependencyBuilder_ == null) {
            dependency_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            dependencyBuilder_.clear();
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_ListWithDependencies_descriptor;
        }

        @java.lang.Override
        public BindingGraphProto.BindingGraph.ListWithDependencies getDefaultInstanceForType() {
          return BindingGraphProto.BindingGraph.ListWithDependencies.getDefaultInstance();
        }

        @java.lang.Override
        public BindingGraphProto.BindingGraph.ListWithDependencies build() {
          BindingGraphProto.BindingGraph.ListWithDependencies result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public BindingGraphProto.BindingGraph.ListWithDependencies buildPartial() {
          BindingGraphProto.BindingGraph.ListWithDependencies result = new BindingGraphProto.BindingGraph.ListWithDependencies(this);
          int from_bitField0_ = bitField0_;
          if (dependencyBuilder_ == null) {
            if (((bitField0_ & 0x00000001) != 0)) {
              dependency_ = java.util.Collections.unmodifiableList(dependency_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.dependency_ = dependency_;
          } else {
            result.dependency_ = dependencyBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof BindingGraphProto.BindingGraph.ListWithDependencies) {
            return mergeFrom((BindingGraphProto.BindingGraph.ListWithDependencies)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(BindingGraphProto.BindingGraph.ListWithDependencies other) {
          if (other == BindingGraphProto.BindingGraph.ListWithDependencies.getDefaultInstance()) return this;
          if (dependencyBuilder_ == null) {
            if (!other.dependency_.isEmpty()) {
              if (dependency_.isEmpty()) {
                dependency_ = other.dependency_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureDependencyIsMutable();
                dependency_.addAll(other.dependency_);
              }
              onChanged();
            }
          } else {
            if (!other.dependency_.isEmpty()) {
              if (dependencyBuilder_.isEmpty()) {
                dependencyBuilder_.dispose();
                dependencyBuilder_ = null;
                dependency_ = other.dependency_;
                bitField0_ = (bitField0_ & ~0x00000001);
                dependencyBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getDependencyFieldBuilder() : null;
              } else {
                dependencyBuilder_.addAllMessages(other.dependency_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          for (int i = 0; i < getDependencyCount(); i++) {
            if (!getDependency(i).isInitialized()) {
              return false;
            }
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          BindingGraphProto.BindingGraph.ListWithDependencies parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (BindingGraphProto.BindingGraph.ListWithDependencies) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.util.List<DependencyProto.Dependency> dependency_ =
          java.util.Collections.emptyList();
        private void ensureDependencyIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            dependency_ = new java.util.ArrayList<DependencyProto.Dependency>(dependency_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            DependencyProto.Dependency, DependencyProto.Dependency.Builder, DependencyProto.DependencyOrBuilder> dependencyBuilder_;

        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public java.util.List<DependencyProto.Dependency> getDependencyList() {
          if (dependencyBuilder_ == null) {
            return java.util.Collections.unmodifiableList(dependency_);
          } else {
            return dependencyBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public int getDependencyCount() {
          if (dependencyBuilder_ == null) {
            return dependency_.size();
          } else {
            return dependencyBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public DependencyProto.Dependency getDependency(int index) {
          if (dependencyBuilder_ == null) {
            return dependency_.get(index);
          } else {
            return dependencyBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public Builder setDependency(
            int index, DependencyProto.Dependency value) {
          if (dependencyBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureDependencyIsMutable();
            dependency_.set(index, value);
            onChanged();
          } else {
            dependencyBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public Builder setDependency(
            int index, DependencyProto.Dependency.Builder builderForValue) {
          if (dependencyBuilder_ == null) {
            ensureDependencyIsMutable();
            dependency_.set(index, builderForValue.build());
            onChanged();
          } else {
            dependencyBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public Builder addDependency(DependencyProto.Dependency value) {
          if (dependencyBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureDependencyIsMutable();
            dependency_.add(value);
            onChanged();
          } else {
            dependencyBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public Builder addDependency(
            int index, DependencyProto.Dependency value) {
          if (dependencyBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureDependencyIsMutable();
            dependency_.add(index, value);
            onChanged();
          } else {
            dependencyBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public Builder addDependency(
            DependencyProto.Dependency.Builder builderForValue) {
          if (dependencyBuilder_ == null) {
            ensureDependencyIsMutable();
            dependency_.add(builderForValue.build());
            onChanged();
          } else {
            dependencyBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public Builder addDependency(
            int index, DependencyProto.Dependency.Builder builderForValue) {
          if (dependencyBuilder_ == null) {
            ensureDependencyIsMutable();
            dependency_.add(index, builderForValue.build());
            onChanged();
          } else {
            dependencyBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public Builder addAllDependency(
            java.lang.Iterable<? extends DependencyProto.Dependency> values) {
          if (dependencyBuilder_ == null) {
            ensureDependencyIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, dependency_);
            onChanged();
          } else {
            dependencyBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public Builder clearDependency() {
          if (dependencyBuilder_ == null) {
            dependency_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            dependencyBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public Builder removeDependency(int index) {
          if (dependencyBuilder_ == null) {
            ensureDependencyIsMutable();
            dependency_.remove(index);
            onChanged();
          } else {
            dependencyBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public DependencyProto.Dependency.Builder getDependencyBuilder(
            int index) {
          return getDependencyFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public DependencyProto.DependencyOrBuilder getDependencyOrBuilder(
            int index) {
          if (dependencyBuilder_ == null) {
            return dependency_.get(index);  } else {
            return dependencyBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public java.util.List<? extends DependencyProto.DependencyOrBuilder>
             getDependencyOrBuilderList() {
          if (dependencyBuilder_ != null) {
            return dependencyBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(dependency_);
          }
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public DependencyProto.Dependency.Builder addDependencyBuilder() {
          return getDependencyFieldBuilder().addBuilder(
              DependencyProto.Dependency.getDefaultInstance());
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public DependencyProto.Dependency.Builder addDependencyBuilder(
            int index) {
          return getDependencyFieldBuilder().addBuilder(
              index, DependencyProto.Dependency.getDefaultInstance());
        }
        /**
         * <code>repeated .dagerquery.models.Dependency dependency = 1;</code>
         */
        public java.util.List<DependencyProto.Dependency.Builder>
             getDependencyBuilderList() {
          return getDependencyFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            DependencyProto.Dependency, DependencyProto.Dependency.Builder, DependencyProto.DependencyOrBuilder>
            getDependencyFieldBuilder() {
          if (dependencyBuilder_ == null) {
            dependencyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                DependencyProto.Dependency, DependencyProto.Dependency.Builder, DependencyProto.DependencyOrBuilder>(
                    dependency_,
                    ((bitField0_ & 0x00000001) != 0),
                    getParentForChildren(),
                    isClean());
            dependency_ = null;
          }
          return dependencyBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:dagerquery.models.BindingGraph.ListWithDependencies)
      }

      // @@protoc_insertion_point(class_scope:dagerquery.models.BindingGraph.ListWithDependencies)
      private static final BindingGraphProto.BindingGraph.ListWithDependencies DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new BindingGraphProto.BindingGraph.ListWithDependencies();
      }

      public static BindingGraphProto.BindingGraph.ListWithDependencies getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<ListWithDependencies>
          PARSER = new com.google.protobuf.AbstractParser<ListWithDependencies>() {
        @java.lang.Override
        public ListWithDependencies parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ListWithDependencies(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ListWithDependencies> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ListWithDependencies> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public BindingGraphProto.BindingGraph.ListWithDependencies getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ADJACENCY_LIST_FIELD_NUMBER = 1;
    private static final class AdjacencyListDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies>newDefaultInstance(
                  BindingGraphProto.internal_static_dagerquery_models_BindingGraph_AdjacencyListEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  BindingGraphProto.BindingGraph.ListWithDependencies.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> adjacencyList_;
    private com.google.protobuf.MapField<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies>
    internalGetAdjacencyList() {
      if (adjacencyList_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AdjacencyListDefaultEntryHolder.defaultEntry);
      }
      return adjacencyList_;
    }

    public int getAdjacencyListCount() {
      return internalGetAdjacencyList().getMap().size();
    }
    /**
     * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
     */

    @java.lang.Override
    public boolean containsAdjacencyList(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAdjacencyList().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAdjacencyListMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> getAdjacencyList() {
      return getAdjacencyListMap();
    }
    /**
     * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> getAdjacencyListMap() {
      return internalGetAdjacencyList().getMap();
    }
    /**
     * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
     */
    @java.lang.Override

    public BindingGraphProto.BindingGraph.ListWithDependencies getAdjacencyListOrDefault(
        java.lang.String key,
        BindingGraphProto.BindingGraph.ListWithDependencies defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> map =
          internalGetAdjacencyList().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
     */
    @java.lang.Override

    public BindingGraphProto.BindingGraph.ListWithDependencies getAdjacencyListOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> map =
          internalGetAdjacencyList().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (BindingGraphProto.BindingGraph.ListWithDependencies item : getAdjacencyListMap().values()) {
        if (!item.isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAdjacencyList(),
          AdjacencyListDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> entry
           : internalGetAdjacencyList().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies>
        adjacencyList__ = AdjacencyListDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, adjacencyList__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof BindingGraphProto.BindingGraph)) {
        return super.equals(obj);
      }
      BindingGraphProto.BindingGraph other = (BindingGraphProto.BindingGraph) obj;

      if (!internalGetAdjacencyList().equals(
          other.internalGetAdjacencyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetAdjacencyList().getMap().isEmpty()) {
        hash = (37 * hash) + ADJACENCY_LIST_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAdjacencyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static BindingGraphProto.BindingGraph parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BindingGraphProto.BindingGraph parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BindingGraphProto.BindingGraph parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BindingGraphProto.BindingGraph parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BindingGraphProto.BindingGraph parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static BindingGraphProto.BindingGraph parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static BindingGraphProto.BindingGraph parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BindingGraphProto.BindingGraph parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static BindingGraphProto.BindingGraph parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static BindingGraphProto.BindingGraph parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static BindingGraphProto.BindingGraph parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static BindingGraphProto.BindingGraph parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(BindingGraphProto.BindingGraph prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dagerquery.models.BindingGraph}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dagerquery.models.BindingGraph)
        BindingGraphProto.BindingGraphOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetAdjacencyList();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableAdjacencyList();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BindingGraphProto.BindingGraph.class, BindingGraphProto.BindingGraph.Builder.class);
      }

      // Construct using com.google.daggerquery.protobuf.autogen.BindingGraphProto.BindingGraph.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableAdjacencyList().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BindingGraphProto.internal_static_dagerquery_models_BindingGraph_descriptor;
      }

      @java.lang.Override
      public BindingGraphProto.BindingGraph getDefaultInstanceForType() {
        return BindingGraphProto.BindingGraph.getDefaultInstance();
      }

      @java.lang.Override
      public BindingGraphProto.BindingGraph build() {
        BindingGraphProto.BindingGraph result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public BindingGraphProto.BindingGraph buildPartial() {
        BindingGraphProto.BindingGraph result = new BindingGraphProto.BindingGraph(this);
        int from_bitField0_ = bitField0_;
        result.adjacencyList_ = internalGetAdjacencyList();
        result.adjacencyList_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof BindingGraphProto.BindingGraph) {
          return mergeFrom((BindingGraphProto.BindingGraph)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(BindingGraphProto.BindingGraph other) {
        if (other == BindingGraphProto.BindingGraph.getDefaultInstance()) return this;
        internalGetMutableAdjacencyList().mergeFrom(
            other.internalGetAdjacencyList());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (BindingGraphProto.BindingGraph.ListWithDependencies item : getAdjacencyListMap().values()) {
          if (!item.isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        BindingGraphProto.BindingGraph parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (BindingGraphProto.BindingGraph) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> adjacencyList_;
      private com.google.protobuf.MapField<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies>
      internalGetAdjacencyList() {
        if (adjacencyList_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AdjacencyListDefaultEntryHolder.defaultEntry);
        }
        return adjacencyList_;
      }
      private com.google.protobuf.MapField<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies>
      internalGetMutableAdjacencyList() {
        onChanged();;
        if (adjacencyList_ == null) {
          adjacencyList_ = com.google.protobuf.MapField.newMapField(
              AdjacencyListDefaultEntryHolder.defaultEntry);
        }
        if (!adjacencyList_.isMutable()) {
          adjacencyList_ = adjacencyList_.copy();
        }
        return adjacencyList_;
      }

      public int getAdjacencyListCount() {
        return internalGetAdjacencyList().getMap().size();
      }
      /**
       * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
       */

      @java.lang.Override
      public boolean containsAdjacencyList(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAdjacencyList().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAdjacencyListMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> getAdjacencyList() {
        return getAdjacencyListMap();
      }
      /**
       * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> getAdjacencyListMap() {
        return internalGetAdjacencyList().getMap();
      }
      /**
       * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
       */
      @java.lang.Override

      public BindingGraphProto.BindingGraph.ListWithDependencies getAdjacencyListOrDefault(
          java.lang.String key,
          BindingGraphProto.BindingGraph.ListWithDependencies defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> map =
            internalGetAdjacencyList().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
       */
      @java.lang.Override

      public BindingGraphProto.BindingGraph.ListWithDependencies getAdjacencyListOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> map =
            internalGetAdjacencyList().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAdjacencyList() {
        internalGetMutableAdjacencyList().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
       */

      public Builder removeAdjacencyList(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdjacencyList().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies>
      getMutableAdjacencyList() {
        return internalGetMutableAdjacencyList().getMutableMap();
      }
      /**
       * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
       */
      public Builder putAdjacencyList(
          java.lang.String key,
          BindingGraphProto.BindingGraph.ListWithDependencies value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAdjacencyList().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .dagerquery.models.BindingGraph.ListWithDependencies&gt; adjacency_list = 1;</code>
       */

      public Builder putAllAdjacencyList(
          java.util.Map<java.lang.String, BindingGraphProto.BindingGraph.ListWithDependencies> values) {
        internalGetMutableAdjacencyList().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dagerquery.models.BindingGraph)
    }

    // @@protoc_insertion_point(class_scope:dagerquery.models.BindingGraph)
    private static final BindingGraphProto.BindingGraph DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BindingGraphProto.BindingGraph();
    }

    public static BindingGraphProto.BindingGraph getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BindingGraph>
        PARSER = new com.google.protobuf.AbstractParser<BindingGraph>() {
      @java.lang.Override
      public BindingGraph parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BindingGraph(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BindingGraph> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BindingGraph> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public BindingGraphProto.BindingGraph getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dagerquery_models_BindingGraph_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dagerquery_models_BindingGraph_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dagerquery_models_BindingGraph_ListWithDependencies_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dagerquery_models_BindingGraph_ListWithDependencies_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dagerquery_models_BindingGraph_AdjacencyListEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dagerquery_models_BindingGraph_AdjacencyListEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023binding_graph.proto\022\021dagerquery.models" +
      "\0320com/google/daggerquery/protobuf/depend" +
      "ency.proto\"\221\002\n\014BindingGraph\022J\n\016adjacency" +
      "_list\030\001 \003(\01322.dagerquery.models.BindingG" +
      "raph.AdjacencyListEntry\032I\n\024ListWithDepen" +
      "dencies\0221\n\ndependency\030\001 \003(\0132\035.dagerquery" +
      ".models.Dependency\032j\n\022AdjacencyListEntry" +
      "\022\013\n\003key\030\001 \001(\t\022C\n\005value\030\002 \001(\01324.dagerquer" +
      "y.models.BindingGraph.ListWithDependenci" +
      "es:\0028\001B4\n\037com.google.daggerquery.protobu" +
      "fB\021BindingGraphProto"
    };

    internal_static_dagerquery_models_BindingGraph_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dagerquery_models_BindingGraph_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dagerquery_models_BindingGraph_descriptor,
        new java.lang.String[] { "AdjacencyList", });
    internal_static_dagerquery_models_BindingGraph_ListWithDependencies_descriptor =
      internal_static_dagerquery_models_BindingGraph_descriptor.getNestedTypes().get(0);
    internal_static_dagerquery_models_BindingGraph_ListWithDependencies_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dagerquery_models_BindingGraph_ListWithDependencies_descriptor,
        new java.lang.String[] { "Dependency", });
    internal_static_dagerquery_models_BindingGraph_AdjacencyListEntry_descriptor =
      internal_static_dagerquery_models_BindingGraph_descriptor.getNestedTypes().get(1);
    internal_static_dagerquery_models_BindingGraph_AdjacencyListEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dagerquery_models_BindingGraph_AdjacencyListEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    DependencyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
