// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dependency.proto

package com.google.daggerquery.protobuf.autogen;

public final class DependencyProto {
  private DependencyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DependencyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dagerquery.models.Dependency)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string target = 1;</code>
     * @return Whether the target field is set.
     */
    boolean hasTarget();
    /**
     * <code>required string target = 1;</code>
     * @return The target.
     */
    java.lang.String getTarget();
    /**
     * <code>required string target = 1;</code>
     * @return The bytes for target.
     */
    com.google.protobuf.ByteString
        getTargetBytes();

    /**
     * <code>optional .dagerquery.models.Dependency.RequestKind request_kind = 2;</code>
     * @return Whether the requestKind field is set.
     */
    boolean hasRequestKind();
    /**
     * <code>optional .dagerquery.models.Dependency.RequestKind request_kind = 2;</code>
     * @return The requestKind.
     */
    DependencyProto.Dependency.RequestKind getRequestKind();

    /**
     * <code>optional string element = 3;</code>
     * @return Whether the element field is set.
     */
    boolean hasElement();
    /**
     * <code>optional string element = 3;</code>
     * @return The element.
     */
    java.lang.String getElement();
    /**
     * <code>optional string element = 3;</code>
     * @return The bytes for element.
     */
    com.google.protobuf.ByteString
        getElementBytes();
  }
  /**
   * Protobuf type {@code dagerquery.models.Dependency}
   */
  public static final class Dependency extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dagerquery.models.Dependency)
      DependencyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dependency.newBuilder() to construct.
    private Dependency(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dependency() {
      target_ = "";
      requestKind_ = 0;
      element_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dependency(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              target_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              DependencyProto.Dependency.RequestKind value = DependencyProto.Dependency.RequestKind.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                requestKind_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              element_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DependencyProto.internal_static_dagerquery_models_Dependency_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DependencyProto.internal_static_dagerquery_models_Dependency_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DependencyProto.Dependency.class, DependencyProto.Dependency.Builder.class);
    }

    /**
     * Protobuf enum {@code dagerquery.models.Dependency.RequestKind}
     */
    public enum RequestKind
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INSTANCE = 0;</code>
       */
      INSTANCE(0),
      /**
       * <code>PROVIDER = 1;</code>
       */
      PROVIDER(1),
      /**
       * <code>LAZY = 2;</code>
       */
      LAZY(2),
      /**
       * <code>PROVIDER_OF_LAZY = 3;</code>
       */
      PROVIDER_OF_LAZY(3),
      /**
       * <code>MEMBERS_INJECTION = 4;</code>
       */
      MEMBERS_INJECTION(4),
      /**
       * <code>PRODUCER = 5;</code>
       */
      PRODUCER(5),
      /**
       * <code>PRODUCED = 6;</code>
       */
      PRODUCED(6),
      /**
       * <code>FUTURE = 7;</code>
       */
      FUTURE(7),
      ;

      /**
       * <code>INSTANCE = 0;</code>
       */
      public static final int INSTANCE_VALUE = 0;
      /**
       * <code>PROVIDER = 1;</code>
       */
      public static final int PROVIDER_VALUE = 1;
      /**
       * <code>LAZY = 2;</code>
       */
      public static final int LAZY_VALUE = 2;
      /**
       * <code>PROVIDER_OF_LAZY = 3;</code>
       */
      public static final int PROVIDER_OF_LAZY_VALUE = 3;
      /**
       * <code>MEMBERS_INJECTION = 4;</code>
       */
      public static final int MEMBERS_INJECTION_VALUE = 4;
      /**
       * <code>PRODUCER = 5;</code>
       */
      public static final int PRODUCER_VALUE = 5;
      /**
       * <code>PRODUCED = 6;</code>
       */
      public static final int PRODUCED_VALUE = 6;
      /**
       * <code>FUTURE = 7;</code>
       */
      public static final int FUTURE_VALUE = 7;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestKind valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static RequestKind forNumber(int value) {
        switch (value) {
          case 0: return INSTANCE;
          case 1: return PROVIDER;
          case 2: return LAZY;
          case 3: return PROVIDER_OF_LAZY;
          case 4: return MEMBERS_INJECTION;
          case 5: return PRODUCER;
          case 6: return PRODUCED;
          case 7: return FUTURE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestKind>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestKind> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestKind>() {
              public RequestKind findValueByNumber(int number) {
                return RequestKind.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return DependencyProto.Dependency.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestKind[] VALUES = values();

      public static RequestKind valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestKind(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dagerquery.models.Dependency.RequestKind)
    }

    private int bitField0_;
    public static final int TARGET_FIELD_NUMBER = 1;
    private volatile java.lang.Object target_;
    /**
     * <code>required string target = 1;</code>
     * @return Whether the target field is set.
     */
    @java.lang.Override
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string target = 1;</code>
     * @return The target.
     */
    @java.lang.Override
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          target_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string target = 1;</code>
     * @return The bytes for target.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_KIND_FIELD_NUMBER = 2;
    private int requestKind_;
    /**
     * <code>optional .dagerquery.models.Dependency.RequestKind request_kind = 2;</code>
     * @return Whether the requestKind field is set.
     */
    @java.lang.Override public boolean hasRequestKind() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .dagerquery.models.Dependency.RequestKind request_kind = 2;</code>
     * @return The requestKind.
     */
    @java.lang.Override public DependencyProto.Dependency.RequestKind getRequestKind() {
      @SuppressWarnings("deprecation")
      DependencyProto.Dependency.RequestKind result = DependencyProto.Dependency.RequestKind.valueOf(requestKind_);
      return result == null ? DependencyProto.Dependency.RequestKind.INSTANCE : result;
    }

    public static final int ELEMENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object element_;
    /**
     * <code>optional string element = 3;</code>
     * @return Whether the element field is set.
     */
    @java.lang.Override
    public boolean hasElement() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string element = 3;</code>
     * @return The element.
     */
    @java.lang.Override
    public java.lang.String getElement() {
      java.lang.Object ref = element_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          element_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string element = 3;</code>
     * @return The bytes for element.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getElementBytes() {
      java.lang.Object ref = element_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        element_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTarget()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, target_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, requestKind_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, element_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, target_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, requestKind_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, element_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DependencyProto.Dependency)) {
        return super.equals(obj);
      }
      DependencyProto.Dependency other = (DependencyProto.Dependency) obj;

      if (hasTarget() != other.hasTarget()) return false;
      if (hasTarget()) {
        if (!getTarget()
            .equals(other.getTarget())) return false;
      }
      if (hasRequestKind() != other.hasRequestKind()) return false;
      if (hasRequestKind()) {
        if (requestKind_ != other.requestKind_) return false;
      }
      if (hasElement() != other.hasElement()) return false;
      if (hasElement()) {
        if (!getElement()
            .equals(other.getElement())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTarget()) {
        hash = (37 * hash) + TARGET_FIELD_NUMBER;
        hash = (53 * hash) + getTarget().hashCode();
      }
      if (hasRequestKind()) {
        hash = (37 * hash) + REQUEST_KIND_FIELD_NUMBER;
        hash = (53 * hash) + requestKind_;
      }
      if (hasElement()) {
        hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getElement().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DependencyProto.Dependency parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DependencyProto.Dependency parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DependencyProto.Dependency parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DependencyProto.Dependency parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DependencyProto.Dependency parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DependencyProto.Dependency parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DependencyProto.Dependency parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DependencyProto.Dependency parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DependencyProto.Dependency parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DependencyProto.Dependency parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DependencyProto.Dependency parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DependencyProto.Dependency parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DependencyProto.Dependency prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dagerquery.models.Dependency}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dagerquery.models.Dependency)
        DependencyProto.DependencyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DependencyProto.internal_static_dagerquery_models_Dependency_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DependencyProto.internal_static_dagerquery_models_Dependency_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DependencyProto.Dependency.class, DependencyProto.Dependency.Builder.class);
      }

      // Construct using com.google.daggerquery.protobuf.autogen.DependencyProto.Dependency.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        target_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        requestKind_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        element_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DependencyProto.internal_static_dagerquery_models_Dependency_descriptor;
      }

      @java.lang.Override
      public DependencyProto.Dependency getDefaultInstanceForType() {
        return DependencyProto.Dependency.getDefaultInstance();
      }

      @java.lang.Override
      public DependencyProto.Dependency build() {
        DependencyProto.Dependency result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public DependencyProto.Dependency buildPartial() {
        DependencyProto.Dependency result = new DependencyProto.Dependency(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.target_ = target_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.requestKind_ = requestKind_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.element_ = element_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DependencyProto.Dependency) {
          return mergeFrom((DependencyProto.Dependency)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DependencyProto.Dependency other) {
        if (other == DependencyProto.Dependency.getDefaultInstance()) return this;
        if (other.hasTarget()) {
          bitField0_ |= 0x00000001;
          target_ = other.target_;
          onChanged();
        }
        if (other.hasRequestKind()) {
          setRequestKind(other.getRequestKind());
        }
        if (other.hasElement()) {
          bitField0_ |= 0x00000004;
          element_ = other.element_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTarget()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DependencyProto.Dependency parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DependencyProto.Dependency) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object target_ = "";
      /**
       * <code>required string target = 1;</code>
       * @return Whether the target field is set.
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string target = 1;</code>
       * @return The target.
       */
      public java.lang.String getTarget() {
        java.lang.Object ref = target_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            target_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string target = 1;</code>
       * @return The bytes for target.
       */
      public com.google.protobuf.ByteString
          getTargetBytes() {
        java.lang.Object ref = target_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          target_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string target = 1;</code>
       * @param value The target to set.
       * @return This builder for chaining.
       */
      public Builder setTarget(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        target_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string target = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTarget() {
        bitField0_ = (bitField0_ & ~0x00000001);
        target_ = getDefaultInstance().getTarget();
        onChanged();
        return this;
      }
      /**
       * <code>required string target = 1;</code>
       * @param value The bytes for target to set.
       * @return This builder for chaining.
       */
      public Builder setTargetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        target_ = value;
        onChanged();
        return this;
      }

      private int requestKind_ = 0;
      /**
       * <code>optional .dagerquery.models.Dependency.RequestKind request_kind = 2;</code>
       * @return Whether the requestKind field is set.
       */
      @java.lang.Override public boolean hasRequestKind() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .dagerquery.models.Dependency.RequestKind request_kind = 2;</code>
       * @return The requestKind.
       */
      @java.lang.Override
      public DependencyProto.Dependency.RequestKind getRequestKind() {
        @SuppressWarnings("deprecation")
        DependencyProto.Dependency.RequestKind result = DependencyProto.Dependency.RequestKind.valueOf(requestKind_);
        return result == null ? DependencyProto.Dependency.RequestKind.INSTANCE : result;
      }
      /**
       * <code>optional .dagerquery.models.Dependency.RequestKind request_kind = 2;</code>
       * @param value The requestKind to set.
       * @return This builder for chaining.
       */
      public Builder setRequestKind(DependencyProto.Dependency.RequestKind value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        requestKind_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .dagerquery.models.Dependency.RequestKind request_kind = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestKind() {
        bitField0_ = (bitField0_ & ~0x00000002);
        requestKind_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object element_ = "";
      /**
       * <code>optional string element = 3;</code>
       * @return Whether the element field is set.
       */
      public boolean hasElement() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string element = 3;</code>
       * @return The element.
       */
      public java.lang.String getElement() {
        java.lang.Object ref = element_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            element_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string element = 3;</code>
       * @return The bytes for element.
       */
      public com.google.protobuf.ByteString
          getElementBytes() {
        java.lang.Object ref = element_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          element_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string element = 3;</code>
       * @param value The element to set.
       * @return This builder for chaining.
       */
      public Builder setElement(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        element_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string element = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearElement() {
        bitField0_ = (bitField0_ & ~0x00000004);
        element_ = getDefaultInstance().getElement();
        onChanged();
        return this;
      }
      /**
       * <code>optional string element = 3;</code>
       * @param value The bytes for element to set.
       * @return This builder for chaining.
       */
      public Builder setElementBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        element_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dagerquery.models.Dependency)
    }

    // @@protoc_insertion_point(class_scope:dagerquery.models.Dependency)
    private static final DependencyProto.Dependency DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DependencyProto.Dependency();
    }

    public static DependencyProto.Dependency getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Dependency>
        PARSER = new com.google.protobuf.AbstractParser<Dependency>() {
      @java.lang.Override
      public Dependency parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dependency(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dependency> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dependency> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public DependencyProto.Dependency getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dagerquery_models_Dependency_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dagerquery_models_Dependency_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020dependency.proto\022\021dagerquery.models\"\371\001" +
      "\n\nDependency\022\016\n\006target\030\001 \002(\t\022?\n\014request_" +
      "kind\030\002 \001(\0162).dagerquery.models.Dependenc" +
      "y.RequestKind\022\017\n\007element\030\003 \001(\t\"\210\001\n\013Reque" +
      "stKind\022\014\n\010INSTANCE\020\000\022\014\n\010PROVIDER\020\001\022\010\n\004LA" +
      "ZY\020\002\022\024\n\020PROVIDER_OF_LAZY\020\003\022\025\n\021MEMBERS_IN" +
      "JECTION\020\004\022\014\n\010PRODUCER\020\005\022\014\n\010PRODUCED\020\006\022\n\n" +
      "\006FUTURE\020\007B2\n\037com.google.daggerquery.prot" +
      "obufB\017DependencyProto"
    };

    internal_static_dagerquery_models_Dependency_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dagerquery_models_Dependency_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dagerquery_models_Dependency_descriptor,
        new java.lang.String[] { "Target", "RequestKind", "Element", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
